language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
      - platform-tools
      - tools

    # The BuildTools version used by your project
      - build-tools-22.0.1

    # The SDK version used to compile your project
      - android-22
      - android-21

    # Additional components
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      - extra-android-support

#install: true # Override install task to prevent duplicate assembleDebug task

sudo: false

before_install:

  # Install base Android SDK
  #- sudo apt-get update -qq
  #- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi

script: ./gradlew -i test
